config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :lists, except: [:index] do
    resources :bookmarks, only: [:new, :create]
  end
  delete '/bookmarks/:id', to: 'bookmarks#destroy', as: :delete_bookmark
  root to: "lists#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list, dependent: :destroy

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :list
  validates :comment, presence: true
  validates :rating, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    # @list = List.find(params[:id])
    @bookmark = Bookmark.find(params[:id])
    @bookmark.delete
    redirect_to root_path
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
before_action :find_list, only: [:show]
  def index
    @lists = List.all
  end

  def show
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save
    redirect_to root_path
  end

  private

  def find_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/bookmarks/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-6">
      <%= simple_form_for [@list, @bookmark] do |f| %>
        <%= f.input :comment %>
        <%= f.association :movie %>
        <%= f.submit "create" %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<nav class=" container d-flex align-items-center justify-content-between">
  <div class='img'><%= image_tag("popcorn.png")%></div>
  <div><%= link_to "new list", new_list_path %></div>
</nav>

<div class='text-center backgroundimg pt-5'>
  <h1>save any kind of movies</h1>
  <h2>classic</h2>
</div>

<div class="container pt-3">
  <div class="row">
    <div class="col-6">
      <div>My Lists</div>
      <% @lists.each do |list| %>
      <div class="align-lists">
        <div><%= link_to list.name, list_path(list), class:"listdiv" %></div>
      </div>
      <% end %>
      <hr>
    </div>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-6">
      <%= simple_form_for @list do |f| %>
        <%= f.input :name %>
        <%= f.submit 'create' %>
      <% end %>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<nav class=" container d-flex align-items-center justify-content-between">
  <div class='img'><%= image_tag("popcorn.png")%></div>
  <div><%= link_to "new list", new_list_path %></div>
</nav>

<div class='text-center backgroundimg pt-5'>
  <h1>save any kind of movies</h1>
  <h2><%= @list.name %></h2>
</div>
<div class="container">
  <div class="row">
    <div class="col-6">
    <%= link_to "add new bookmarkt", new_list_bookmark_path(@list), class:'btn btn-success my-3' %>
    <div class="list-grid">
      <% @list.bookmarks.each do |bookmark| %>
      <div class="align-list">
      <div class="w-100"><%= image_tag(bookmark.movie.poster_url, width: 400, height: 300, crop: :fill) %></div>
        <div><%= bookmark.movie.title %></div>
        <div><%= bookmark.movie.overview %></div>
        <div class="d-flex justify-content-between"><div>&& <%= bookmark.comment %></div><%= link_to "delete", delete_bookmark_path(bookmark), method: :delete %></div>
      <% end %>
      </div>
    </div>
    </div>
  </div>
</div>